### ISSUE TITLE
rv32-ima

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [google/esh#3]
Does it work for rv32-ima platform?

**Comment by dstreetdog** [comment]
@ElectroBoy404NotFound :

> Does it work for rv32-ima platform?

Yes. It should work. Use this as reference: [examples/physical/hifive/Makefile#L26](https://github.com/google/esh/blob/a84a98d4da19d281130f87334eea808e5651f211/examples/physical/hifive/Makefile#L26)

Changing, `-march=rv32imac` to `-march=rv32ima` should work (I haven't specifically tried this). Also, is there a specific platform you want to try this on?

**Comment by ElectroBoy404NotFound** [comment]
> @ElectroBoy404NotFound :
> 
> > Does it work for rv32-ima platform?
> 
> Yes. It should work. Use this as reference: [examples/physical/hifive/Makefile#L26](https://github.com/google/esh/blob/a84a98d4da19d281130f87334eea808e5651f211/examples/physical/hifive/Makefile#L26)
> 
> Changing, `-march=rv32imac` to `-march=rv32ima` should work (I haven't specifically tried this). Also, is there a specific platform you want to try this on?

I'm trying this on [mini-rv32ima](https://github.com/cnlohr/mini-rv32ima)

**Comment by ElectroBoy404NotFound** [comment]
It isn't working. The build image isn't booting!

**Comment by dstreetdog** [comment]
some clarification,

> Does it work for the rv32-ima platform?

For this, I assumed you were trying to compile for the `ima` extension of the `RISC-V 32` CPU (and referred to that as the platform). The code should compile for that based on my [comment](https://github.com/google/esh/issues/3#issuecomment-1620179998).

> It isn't working. The build image isn't booting!

If attempting to boot `esh` on `mini-rv32ima`, the startup sequence, the linker script, and the memory addresses in the Makefile would need some edits. 

Could you share more details on how you are trying to boot?

**Comment by ElectroBoy404NotFound** [comment]
> 

Ah, i was trying to boot after compiling it directly. Then i tried to run it using the above mentioned platform, it gave nothing on the screen nor done anything.

**Comment by dstreetdog** [comment]
That makes sense. The way shell works, it takes control of the CPU at the very early stage (quickly after boot). Because you are attempting a port on a new platform, the [Setting up new project](https://github.com/google/esh/blob/main/docs/index.md) part of the documentation might help.

In the meantime, can you point me to the Address map of this platform? I can guide you further on how to do the port.

**Comment by ElectroBoy404NotFound** [comment]
Hi!


> That makes sense. The way shell works, it takes control of the CPU at the very early stage (quickly after boot). Because you are attempting a port on a new platform, the [Setting up new project](https://github.com/google/esh/blob/main/docs/index.md) part of the documentation might help.
> 
> In the meantime, can you point me to the Address map of this platform? I can guide you further on how to do the port.

This is the Address map i know: 
0x10000000 :- UART (8250 / 16550)
0x11100000 :- SYSCON
0x11004000 :- CLNT
0x11004004 :- CLNT
0x80000000 :- RAM (16MB)


The image is loaded into RAM before being run.

**Comment by ElectroBoy404NotFound** [comment]
I found a linker file for this platform:
[flatfile.lds](https://raw.githubusercontent.com/cnlohr/mini-rv32ima/master/baremetal/flatfile.lds)

**Comment by ElectroBoy404NotFound** [comment]
Hi,
I ported it to my platform by modifying everyhting necessory. It is working now. Thank you!

**Comment by streetdogg** [comment]
Awesome and Kudos!
